do
$$
BEGIN
RAISE NOTICE 'Create table staging.FACT_Продажи.Товары';
END;
$$;
CREATE TABLE IF NOT EXISTS staging."FACT_Продажи_Товары" (
    staging_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id                bigint NULL,
    session_id        bigint NULL,
    source_name       varchar(128) NULL,
    nkey              uuid NOT NULL,
    vkey              uuid NOT NULL,
    start_date        timestamp without time zone NULL,
    end_date          timestamp without time zone NULL,
    "FACT_ПродажиRefID"            uuid  NULL,
    "Доставка"            boolean  NULL,
    "Товар"            varchar(36)  NULL,
    "Колличество"            decimal(12, 0)  NULL,
    "Цена"            decimal(16, 4)  NULL,
    session_id_update bigint NOT NULL,
    dt_update         timestamp without time zone        NULL
);
