do
$$
BEGIN
RAISE NOTICE 'Create table staging.DIM_Валюты.Представления';
END;
$$;
CREATE TABLE IF NOT EXISTS staging."DIM_Валюты_Представления" (
    staging_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id                bigint NULL,
    session_id        bigint NULL,
    source_name       varchar(128) NULL,
    nkey              uuid NOT NULL,
    vkey              uuid NOT NULL,
    start_date        timestamp without time zone NULL,
    end_date          timestamp without time zone NULL,
    "DIM_ВалютыRefID"            uuid  NULL,
    "КодЯзыка"            varchar(10)  NULL,
    "ПараметрыПрописи"            varchar(200)  NULL,
    session_id_update bigint NOT NULL,
    dt_update         timestamp without time zone        NULL
);
