do
$$
BEGIN
RAISE NOTICE 'Create table FACT_Продажи';
END;
$$;

CREATE TABLE IF NOT EXISTS odins."FACT_Продажи" (
    ods_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    nkey          uuid NOT NULL,
    "RefID"        uuid  NOT NULL  ,
    "DeletionMark"        boolean   NULL  ,
    "Number"        integer   NULL  ,
    "Posted"        boolean   NULL  ,
    "Date"        timestamp   NULL  ,
    "ДатаОтгрузки"        timestamp   NULL  ,
    "Клиент"        varchar(36)   NULL  ,
    "ТипДоставки"        varchar(500)   NULL  ,
    "ПримерСоставногоТипа"        varchar(36)   NULL  ,
    "ПримерСоставногоТипа_ТипЗначения"        varchar(128)   NULL  ,
    dt_update     timestamp without time zone default now(),
    dt_create     timestamp without time zone default now()
);

COMMENT ON TABLE "odins"."FACT_Продажи" IS '{"Description":"FACT_Продажи"}';

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_odins_FACT_Продажи" ON odins."FACT_Продажи" (nkey);
