do
$$
BEGIN
RAISE NOTICE 'Create table DIM_Валюты';
END;
$$;

CREATE TABLE IF NOT EXISTS odins."DIM_Валюты" (
    ods_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    nkey          uuid NOT NULL,
    "RefID"        uuid  NOT NULL  ,
    "DeletionMark"        boolean   NULL  ,
    "Code"        varchar(128)   NULL  ,
    "Description"        varchar(128)   NULL  ,
    "ЗагружаетсяИзИнтернета"        boolean   NULL  ,
    "НаименованиеПолное"        varchar(50)   NULL  ,
    "Наценка"        decimal(10, 2)   NULL  ,
    "ОсновнаяВалюта"        varchar(36)   NULL  ,
    "ПараметрыПрописи"        varchar(200)   NULL  ,
    "ФормулаРасчетаКурса"        varchar(100)   NULL  ,
    "СпособУстановкиКурса"        varchar(500)   NULL  ,
    dt_update     timestamp without time zone default now(),
    dt_create     timestamp without time zone default now()
);

COMMENT ON TABLE "odins"."DIM_Валюты" IS '{"Description":"DIM_Валюты"}';

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_odins_DIM_Валюты" ON odins."DIM_Валюты" (nkey);
