do
$$
BEGIN
RAISE NOTICE 'Create table DIM_Товары';
END;
$$;

CREATE TABLE IF NOT EXISTS odins."DIM_Товары" (
    ods_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    nkey          uuid NOT NULL,
    "RefID"        uuid  NOT NULL  ,
    "DeletionMark"        boolean   NULL  ,
    "Code"        varchar(128)   NULL  ,
    "Description"        varchar(128)   NULL  ,
    "Описание"        varchar(255)   NULL  ,
    dt_update     timestamp without time zone default now(),
    dt_create     timestamp without time zone default now()
);

COMMENT ON TABLE "odins"."DIM_Товары" IS '{"Description":"DIM_Товары"}';

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_odins_DIM_Товары" ON odins."DIM_Товары" (nkey);
