do
$$
BEGIN
RAISE NOTICE 'Create table FACT_Продажи_Товары';
END;
$$;

CREATE TABLE IF NOT EXISTS odins."FACT_Продажи_Товары" (
    ods_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    nkey          uuid NOT NULL,
    "FACT_ПродажиRefID"        uuid  NOT NULL  ,
    "Доставка"        boolean   NULL  ,
    "Товар"        varchar(36)   NULL  ,
    "Колличество"        decimal(12, 0)   NULL  ,
    "Цена"        decimal(16, 4)   NULL  ,
    dt_update     timestamp without time zone default now(),
    dt_create     timestamp without time zone default now()
);

COMMENT ON TABLE "odins"."FACT_Продажи_Товары" IS '{"Description":"FACT_Продажи.Товары"}';

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_odins_FACT_Продажи_Товары" ON odins."FACT_Продажи_Товары" (nkey);
