do
$$
BEGIN
RAISE NOTICE 'Create table DIM_Валюты_Представления';
END;
$$;

CREATE TABLE IF NOT EXISTS odins."DIM_Валюты_Представления" (
    ods_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    nkey          uuid NOT NULL,
    "DIM_ВалютыRefID"        uuid  NOT NULL  ,
    "КодЯзыка"        varchar(10)   NULL  ,
    "ПараметрыПрописи"        varchar(200)   NULL  ,
    dt_update     timestamp without time zone default now(),
    dt_create     timestamp without time zone default now()
);

COMMENT ON TABLE "odins"."DIM_Валюты_Представления" IS '{"Description":"DIM_Валюты.Представления"}';

CREATE UNIQUE INDEX IF NOT EXISTS "IDX_odins_DIM_Валюты_Представления" ON odins."DIM_Валюты_Представления" (nkey);
