
default_user = admin
default_pass = admin

listeners.tcp.default = 5672

management.tcp.port = 15672
# Traefik PathPrefix /rabbit without StripPrefix (https://www.rabbitmq.com/docs/management#path-prefix)
management.path_prefix = /rabbit

management.load_definitions = /etc/rabbitmq/definitions.json