CREATE TABLE [staging].[FACT_Продажи] (
    [staging_id]        bigint IDENTITY(1,1) NOT NULL,
    [id]                bigint NULL,
    [session_id]        bigint NULL,
    [source_name]       varchar(128) COLLATE Cyrillic_General_CI_AS NULL,
    [nkey]              uniqueidentifier NULL,
    [vkey]              uniqueidentifier NULL,
    [start_date]        datetime NULL,
    [end_date]          datetime NULL,
    [RefID]            uniqueidentifier  NULL,
    [DeletionMark]            bit  NULL,
    [Number]            int  NULL,
    [Posted]            bit  NULL,
    [Date]            datetime2(0)  NULL,
    [DateID]            int  NULL,
    [ДатаОтгрузки]            datetime2(0)  NULL,
    [ДатаОтгрузкиID]            int  NULL,
    [Клиент]            varchar(36)  NULL,
    [ТипДоставки]            varchar(500)  NULL,
    [ПримерСоставногоТипа]            varchar(36)  NULL,
    [ПримерСоставногоТипа_ТипЗначения]            varchar(128)  NULL,
    [session_id_update] bigint NOT NULL,
    [dt_update]         datetime2(4)         NULL);
GO