CREATE TABLE IF NOT EXISTS dwh_session (
    dwh_session_id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    data_source_id       smallint         NOT NULL,
    dwh_session_state_id smallint         NOT NULL,
    create_session       timestamp with time zone,
    error_message        VARCHAR (4000) NULL,
    dt_update            timestamp with time zone NOT NULL default now(),
    dt_create            timestamp with time zone NOT NULL default now()
    
);

