CREATE TABLE IF NOT EXISTS public.metadata_buffer
(
    buffer_id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    session_id  bigint           NOT NULL,
    msg_id      character varying(36) COLLATE pg_catalog."default",
    msg         text COLLATE pg_catalog."default",
    is_error    boolean       CONSTRAINT DF_metadata_buffer_is_error_DEFAULT DEFAULT ((false)) NOT NULL,
    dt_create   timestamp with time zone NOT NULL default now()
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.metadata_buffer
    OWNER to postgres;