do
$$
BEGIN
RAISE NOTICE 'Create table staging.DIM_Клиенты';
END;
$$;
CREATE TABLE IF NOT EXISTS "staging"."DIM_Клиенты" (
    id         bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nkey       uuid NOT NULL,
    "RefID"            uuid  NULL,
    "DeletionMark"            boolean  NULL,
    "Code"            varchar(128)  NULL,
    "Description"            varchar(128)  NULL,
    "Контакт"            varchar(500)  NULL,
    "dt_update"              timestamp without time zone);
