do
$$
BEGIN
RAISE NOTICE 'Create table staging.FACT_Продажи';
END;
$$;
CREATE TABLE IF NOT EXISTS "staging"."FACT_Продажи" (
    id         bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nkey       uuid NOT NULL,
    "RefID"            uuid  NULL,
    "DeletionMark"            boolean  NULL,
    "Number"            integer  NULL,
    "Posted"            boolean  NULL,
    "Date"            timestamp  NULL,
    "ДатаОтгрузки"            timestamp  NULL,
    "Клиент"            varchar(36)  NULL,
    "ТипДоставки"            varchar(500)  NULL,
    "ПримерСоставногоТипа"            varchar(36)  NULL,
    "ПримерСоставногоТипа_ТипЗначения"            varchar(128)  NULL,
    "dt_update"              timestamp without time zone);
