do
$$
BEGIN
RAISE NOTICE 'Create table staging.DIM_Валюты';
END;
$$;
CREATE TABLE IF NOT EXISTS "staging"."DIM_Валюты" (
    id         bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nkey       uuid NOT NULL,
    "RefID"            uuid  NULL,
    "DeletionMark"            boolean  NULL,
    "Code"            varchar(128)  NULL,
    "Description"            varchar(128)  NULL,
    "ЗагружаетсяИзИнтернета"            boolean  NULL,
    "НаименованиеПолное"            varchar(50)  NULL,
    "Наценка"            decimal(10, 2)  NULL,
    "ОсновнаяВалюта"            varchar(36)  NULL,
    "ПараметрыПрописи"            varchar(200)  NULL,
    "ФормулаРасчетаКурса"            varchar(100)  NULL,
    "СпособУстановкиКурса"            varchar(500)  NULL,
    "dt_update"              timestamp without time zone);
