CREATE TABLE IF NOT EXISTS dwh_processing_details (
    processing_id  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    dwh_session_id BIGINT        NULL,
    schema_name    VARCHAR (128) NULL,
    table_name     VARCHAR (128) NULL,
    row_count      BIGINT        NULL
);

