CREATE TABLE IF NOT EXISTS dwh_session_log (
    dwh_session_log_id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) PRIMARY KEY,
    dwh_session_id       BIGINT         NOT NULL,
    dwh_session_state_id smallint        NOT NULL,
    error_message        VARCHAR (4000) NULL,
    dt_create            timestamp with time zone NOT NULL 
);

