
CREATE TABLE IF NOT EXISTS public.filequeue (
    filequeue_id     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) ,
    session_id  bigint  NOT NULL,
    msg_key character varying(256) COLLATE pg_catalog."default" NOT NULL,
    msg_id uuid NULL,
    start_date timestamp with time zone NULL,
    finish_date timestamp with time zone NULL,
    filename character varying(4000) COLLATE pg_catalog."default" NULL,
    filefolder character varying(4000) COLLATE pg_catalog."default" NULL,
    filetype character varying(4) COLLATE pg_catalog."default" NULL,
    error_msg character varying(4000) COLLATE pg_catalog."default" NULL,
    state_id smallint NOT NULL,
    dt_create timestamp with time zone  CONSTRAINT DF_filequeue_create_date_DEFAULT DEFAULT (now()) NOT NULL,
    dt_update timestamp with time zone  CONSTRAINT DF_filequeue_update_date_DEFAULT DEFAULT (now()) NOT NULL,
    CONSTRAINT PK_filequeue PRIMARY KEY (filequeue_id)
);



