
CREATE TABLE IF NOT EXISTS public.msgqueue
(
    buffer_id  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    session_id bigint NOT NULL,
    msg_id uuid NOT NULL,
    msg text COLLATE pg_catalog."default",
    msg_key character varying(128) COLLATE pg_catalog."default",
    dt_create timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_msgqueue" PRIMARY KEY (buffer_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.msgqueue
    OWNER to postgres;