CREATE TABLE IF NOT EXISTS public.session_log 
(

    session_log_id   bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    session_id       bigint   NOT NULL,
    session_state_id smallint  NOT NULL,
    error_message    character varying(4000) COLLATE pg_catalog."default",
    dt_create        timestamp with time zone  CONSTRAINT DF_session_log_date_DEFAULT DEFAULT (now()) NOT NULL,
    CONSTRAINT "PK_session_log" PRIMARY KEY (session_log_id)
);

