
CREATE TABLE IF NOT EXISTS public.session (
    session_id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ) ,
    data_source_id   smallint        NOT NULL,
    session_state_id smallint    NOT NULL,
    error_message    character varying(4000) COLLATE pg_catalog."default" NULL,
    dt_update        timestamp with time zone  CONSTRAINT DF_session_update_date_DEFAULT DEFAULT (now()) NOT NULL,
    dt_create        timestamp with time zone  CONSTRAINT DF_session_create_date_DEFAULT DEFAULT (now()) NOT NULL,
    CONSTRAINT PK_session PRIMARY KEY (session_id)
);



